version: "3"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
  petclinic:
    image: forevergenin/spring-petclinic:dev
    ports:
      - "9090:8080"
    depends_on:
      - mysql
